# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test fc-custom-runtime-packer module when push or pull request to master branch.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish fc-custom-runtime-packer to local maven repository
        run: ./gradlew :fc-custom-runtime-packer:publishToMavenLocal
      - name: "Append 'include demo' into settings.gradle"
        run: echo 'include demo' >> settings.gradle
      - name: Integrate test
        run: ./gradlew :demo:zipBootstrap
